image: maven:3.9.9-eclipse-temurin-21

# Define the stages in the pipeline
stages:
  - build
  - test
  - package
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

# Build Stage
build:
  stage: build
  script:
    - echo variable ci_commit_ref_slug ${CI_COMMIT_REF_SLUG}
    - mvn compile
  only:
    - main

# Test Stage
test:
  stage: test
  script:
    - mvn test -Dmaven.repo.local=.m2/repository
  only:
    - main

# Package Stage
package:
  stage: package
  script:
    - mvn package -DskipTests -Dmaven.repo.local=.m2/repository
    - ls target/*.jar
  artifacts:
    paths:
      - target/*.jar
  only:
    - main

# Deploy Stage
deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # Add your deployment commands here
  only:
    - main
