# Specify the Docker image for this build environment
image: maven:3.9.9-eclipse-temurin-21

# Define the stages in the pipeline
stages:
  - build
  - test
  - package
  - deploy

# Cache to speed up builds
cache:
  paths:
    - .m2/repository

# Build Stage
build:
  stage: build
  script:
    - mvn compile
  only:
    - main

# Test Stage
test:
  stage: test
  script:
    - mvn test
  only:
    - main

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch"
  environment: production
