# Specify the Docker image for this build environment
image: maven:3.9.9-eclipse-temurin-21

# Define the stages in the pipeline
stages:
  - build
  - test
  - package
  - deploy

# Cache to speed up builds
cache:
  paths:
    - $HOME/.m2/repository

# Build Stage
build:
  stage: build
  script:
    - mvn compile -Dmaven.repo.local=$HOME/.m2/repository
  only:
    - main

# Test Stage
test:
  stage: test
  script:
    - mvn test -Dmaven.repo.local=$HOME/.m2/repository
  only:
    - main

# Package Stage
package:
  stage: package
  script:
    - mvn package -DskipTests -Dmaven.repo.local=$HOME/.m2/repository
    - ls target/*.jar
  artifacts:
    paths:
      - target/*.jar
  only:
    - main

# Deploy Stage
deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # Add your deployment commands here
  only:
    - main
