services:

  postgres-db:
    image: postgres:15
    container_name: taco-cloud-db
    restart: on-failure
    environment:
      - POSTGRES_USER=tacouser
      - POSTGRES_PASSWORD=tacopassword
      - POSTGRES_DB=tacocloud
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "3000:8080"

volumes:
  postgres-db:
