server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/baeldung.p12
    key-store-password: mypassword
    key-alias: baeldung
    enabled: true
  
  port: 8443

spring:
  datasource:
    generate-unique-name: false
    name: tacocloud

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    rest:
      base-path: /data-api

  artemis:
    broker-url: tcp://localhost:61616
    user: tacouser
    password: password

  jms:
    template:
      default-destination: tacocloud.order.queue

taco:
  orders:
    pageSize: 10

logging:
  level:
    tacos: debug
---
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/tacocloud
    username: tacouser
    password: tacopassword

  config:
    activate:
      on-profile: prod
      
logging:
  level:
    tacos: info
    org:
      springframework:
        security: debug
        web:
          client: debug