spring:
  datasource:
    url: jdbc:mariadb://localhost/tacocloud
    username: root
    password: oarnud9I
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

taco:
  orders:
    pageSize: 10