spring:
  datasource:
    generate-unique-name: false
    name: tacocloud

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    rest:
      base-path: /data-api

taco:
  orders:
    pageSize: 10

logging:
  level:
    tacos: debug
---
spring:

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

  config:
    activate:
      on-profile: prod
logging:
  level:
    tacos: info
    org:
      springframework:
        security: debug
        web:
          client: debug