[versions]
springBoot = "3.3.7"
springDependencyManagement = "1.1.7"

[plugins]
springBootPlugin = { id = "org.springframework.boot", version.ref = "springBoot" }
springDependencyManagementPlugin = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }